preset: recommended

enabled:
  - long_array_syntax
  - concat_with_spaces

disabled:
  - short_array_syntax
  - concat_without_spaces
  - visibility
  - ordered_use
  - unused_use
  - phpdoc_align
  - blank_line_before_return
